version: 2
jobs:
  build:

    macos:
      xcode: "9.0"

    steps:
    - checkout

      # - run:
      #   name: Go in Example repository
      #   command: cd Example

    - run:
        name: pre-start simulator
        command: xcrun instruments -w "iPhone 6s (11.0) [" || true

    # Build the app and run tests
    - run:
        name: Build and run tests
        command: |
          cd ./Example
          set -o pipefail && xcodebuild
            CODE_SIGNING_REQUIRED=NO
            CODE_SIGN_IDENTITY=
            PROVISIONING_PROFILE=
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 6s'
            -workspace CTKFlagPhoneNumber.xcworkspace
            -scheme "CTKFlagPhoneNumber_ExampleUITests"
            clean build test |
          tee $CIRCLE_ARTIFACTS/xcode_raw.log |
          xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml

        # environment:
        #   SCAN_WORKSPACE: CTKFlagPhoneNumber.xcworkspace
        #   SCAN_DEVICE: iPhone 6s
        #   SCAN_SCHEME: CTKFlagPhoneNumber_ExampleUITests
          # SCAN_CLEAN:  true
          # SCAN_CONFIGURATION: DEBUG
          # SCAN_XCARGS:


workflows:
  version: 2
  build_and_test:
    jobs:
      - build