version: 2
jobs:
  build:
    macos:
      xcode: "8.2"

    steps:
    - checkout

      # - run:
      #   name: Go in Example repository
      #   command: cd Example

    - run:
        name: pre-start simulator
        command: xcrun instruments -w "iPhone 7 (10.2) [" || true

    # Build the app and run tests
    - run:
        name: Build and run tests
        command: |
          cd ./Example
          fastlane scan
        environment:
          SCAN_WORKSPACE: CTKFlagPhoneNumber.xcworkspace
          SCAN_DEVICE: iPhone 6s
          SCAN_SCHEME: CTKFlagPhoneNumber_ExampleUITests
          # SCAN_CLEAN:  true
          # SCAN_CONFIGURATION: DEBUG
          # SCAN_XCARGS:

    # test:
    #   override:
    #     - set -o pipefail &&
    #       xcodebuild
    #         CODE_SIGNING_REQUIRED=NO
    #         CODE_SIGN_IDENTITY=
    #         PROVISIONING_PROFILE=
    #         -sdk iphonesimulator
    #         -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7'
    #         -workspace CTKFlagPhoneNumber.xcworkspace
    #         -scheme "CTKFlagPhoneNumber_ExampleUITests"
    #         clean build test |
    #       tee $CIRCLE_ARTIFACTS/xcode_raw.log |
    #       xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build