version: 2
jobs:
  build:

    working_directory: ./Example

    # Specify the Xcode version to use
    macos:
      xcode: "9.0"

    steps:
    - checkout

    # Build the app and run tests
    - run:
        name: Build and run tests
        command: fastlane scan
        environment:
          SCAN_WORKSPACE: CTKFlagPhoneNumber.xcworkspace
          # SCAN_DEVICE: iPhone 6s
          SCAN_SCHEME: CTKFlagPhoneNumber-Example
          # SCAN_CLEAN:  true
          # SCAN_CONFIGURATION: DEBUG
          # SCAN_XCARGS:
