version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.2"

    dependencies:
      pre:
        - xcrun instruments -w "iPhone 6 (11.2)" || true

    steps:
    - checkout

      # - run:
      #   name: Go in Example repository
      #   command: cd Example

    # Build the app and run tests
    - run:
        name: Build and run tests
        command: |
          cd ./Example
          fastlane scan
        environment:
          SCAN_WORKSPACE: CTKFlagPhoneNumber.xcworkspace
          SCAN_DEVICE: iPhone 6s
          SCAN_SCHEME: CTKFlagPhoneNumber_ExampleUITests
          # SCAN_CLEAN:  true
          # SCAN_CONFIGURATION: DEBUG
          # SCAN_XCARGS:
